### ISSUE TITLE
Err Require ESM

### ISSUE THREAD

**Issue by davidbesteltunts** [kristian/minify-xml#21]
Hello, I'm trying to use the library but I'm getting this error:
```
var import_minify_xml = __toESM(require("minify-xml"));
Error [ERR_REQUIRE_ESM]: require() of ES Module
```

My project is in Typescript, maybe it's some incorrect configuration on my part, but I'd like to ask if you've ever experienced this error?

I'm importing the library this way:
```import minifyXML from 'minify-xml';```

In dist it looks like this:
```var import_minify_xml = __toESM(require("minify-xml"))```

**Comment by kristian** [comment]
I am not really familiar with typescript, but `minify-xml`, like next to all current NodeJS libraries is now using the [ES module](https://nodejs.org/api/esm.html) format, since its 4.0.0 release. The last release supporting the old CommonJS module format / `require` is 3.5.0. I don't know how to instruct TypeScript NOT to transpile an `import` into a `require`, but I would not consider this one a bug of `minify-xml`.

**Comment by davidbesteltunts** [comment]
thanks for the reply, I'll try other alternatives.

**Comment by kristian** [comment]
@davidbesteltunts you are welcome. :) As said, you can also pin to 3.5.0, which still supports require and has no further changes adapted yet. In order to consume ES modules in typescript see [1].

[1] https://www.typescriptlang.org/docs/handbook/modules/reference.html#node16-nodenext
